#!/usr/bin/env python3
"""Build ui/data.js from the latest screener reports.

Scans the reports/ directory for the most recent run date and embeds that run's
Nasdaq-100 and S&P 500 CSV results (plus the summary header counts) into
ui/data.js as a plain JS object. This lets ui/index.html render without any
server or directory-listing: the data travels with the page.

Usage:
    python ui/build_data.py                 # reads ../reports, writes ui/data.js
    python ui/build_data.py REPORTS_DIR     # custom reports directory
"""
import sys
import os
import re
import csv
import glob
import json
import datetime as dt

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_REPORTS = os.path.join(HERE, "..", "reports")

# screener-YYYY-MM-DD[-suffix].csv
NAME_RE = re.compile(r"^screener-(\d{4}-\d{2}-\d{2})(?:-(.+))?\.csv$")

# suffix in the filename -> table key used by the UI
SUFFIX_TO_KEY = {
    "nasdaq_100": "nasdaq100",
    "sp_500": "sp500",
}


def latest_date(reports_dir):
    dates = set()
    for path in glob.glob(os.path.join(reports_dir, "screener-*.csv")):
        m = NAME_RE.match(os.path.basename(path))
        if m:
            dates.add(m.group(1))
    if not dates:
        raise SystemExit(f"No screener CSV reports found in {reports_dir}")
    return max(dates)  # ISO dates sort lexicographically


def read_csv_rows(path):
    with open(path, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def read_summary_counts(csv_path):
    """Pull the candidate/qualifying counts from the sibling .txt summary."""
    txt_path = csv_path[:-4] + ".txt"
    counts = {"candidates": None, "qualifying": None}
    if not os.path.exists(txt_path):
        return counts
    with open(txt_path, encoding="utf-8") as f:
        text = f.read()
    mc = re.search(r"Candidates scanned:\s*(\d+)", text)
    mq = re.search(r"Qualifying tickers:\s*(\d+)", text)
    if mc:
        counts["candidates"] = int(mc.group(1))
    if mq:
        counts["qualifying"] = int(mq.group(1))
    return counts


def main(argv):
    reports_dir = os.path.abspath(argv[1]) if len(argv) > 1 else os.path.abspath(DEFAULT_REPORTS)
    run_date = latest_date(reports_dir)

    tables = {}
    for suffix, key in SUFFIX_TO_KEY.items():
        csv_path = os.path.join(reports_dir, f"screener-{run_date}-{suffix}.csv")
        if not os.path.exists(csv_path):
            tables[key] = {"available": False, "rows": [], "counts": {}}
            continue
        tables[key] = {
            "available": True,
            "rows": read_csv_rows(csv_path),
            "counts": read_summary_counts(csv_path),
        }

    payload = {
        "runDate": run_date,
        "generatedAt": dt.datetime.now().isoformat(timespec="seconds"),
        "tables": tables,
    }

    out_path = os.path.join(HERE, "data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by ui/build_data.py. Do not edit by hand.\n")
        f.write("window.SCREENER_DATA = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")

    print(f"Wrote {out_path} for run {run_date} "
          f"(nasdaq100={len(tables.get('nasdaq100',{}).get('rows',[]))} rows, "
          f"sp500={len(tables.get('sp500',{}).get('rows',[]))} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
