// Auto-generated by ui/build_data.py. Do not edit by hand.
window.SCREENER_DATA = {
  "runDate": "2026-10-08",
  "generatedAt": "2026-10-07T21:09:06",
  "tables": {
    "nasdaq100": {
      "available": true,
      "rows": [
        {
          "ticker": "KLAC",
          "netAppreciation": "1.5488",
          "peRatio": "53.78",
          "strike": "185.0",
          "expiry": "2026-11-06",
          "premium": "7.60",
          "delta": "-0.3200",
          "premiumYield": "0.0411"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "3.1296",
          "peRatio": "57.21",
          "strike": "310.0",
          "expiry": "2026-11-06",
          "premium": "11.85",
          "delta": "-0.3165",
          "premiumYield": "0.0382"
        },
        {
          "ticker": "MRVL",
          "netAppreciation": "2.9150",
          "peRatio": "93.64",
          "strike": "265.0",
          "expiry": "2026-11-06",
          "premium": "9.40",
          "delta": "-0.2944",
          "premiumYield": "0.0355"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.6333",
          "peRatio": "44.92",
          "strike": "490.0",
          "expiry": "2026-11-06",
          "premium": "15.65",
          "delta": "-0.3060",
          "premiumYield": "0.0319"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.6652",
          "peRatio": "14.64",
          "strike": "1025.0",
          "expiry": "2026-11-06",
          "premium": "29.50",
          "delta": "-0.2979",
          "premiumYield": "0.0288"
        },
        {
          "ticker": "TXN",
          "netAppreciation": "0.5102",
          "peRatio": "43.98",
          "strike": "270.0",
          "expiry": "2026-11-06",
          "premium": "6.95",
          "delta": "-0.2802",
          "premiumYield": "0.0257"
        }
      ],
      "counts": {
        "candidates": 25,
        "qualifying": 6
      }
    },
    "sp500": {
      "available": true,
      "rows": [
        {
          "ticker": "RDDT",
          "netAppreciation": "1.1578",
          "peRatio": "35.51",
          "strike": "140.0",
          "expiry": "2026-11-06",
          "premium": "6.40",
          "delta": "-0.2933",
          "premiumYield": "0.0457"
        },
        {
          "ticker": "COHR",
          "netAppreciation": "2.4184",
          "peRatio": "81.20",
          "strike": "305.0",
          "expiry": "2026-11-06",
          "premium": "12.80",
          "delta": "-0.2907",
          "premiumYield": "0.0420"
        },
        {
          "ticker": "KLAC",
          "netAppreciation": "1.5488",
          "peRatio": "53.78",
          "strike": "185.0",
          "expiry": "2026-11-06",
          "premium": "7.60",
          "delta": "-0.3200",
          "premiumYield": "0.0411"
        },
        {
          "ticker": "TER",
          "netAppreciation": "2.2034",
          "peRatio": "56.56",
          "strike": "380.0",
          "expiry": "2026-11-06",
          "premium": "15.50",
          "delta": "-0.3060",
          "premiumYield": "0.0408"
        },
        {
          "ticker": "HUM",
          "netAppreciation": "0.6713",
          "peRatio": "37.48",
          "strike": "365.0",
          "expiry": "2026-11-06",
          "premium": "14.70",
          "delta": "-0.2964",
          "premiumYield": "0.0403"
        },
        {
          "ticker": "SNDK",
          "netAppreciation": "46.0117",
          "peRatio": "22.94",
          "strike": "1570.0",
          "expiry": "2026-11-06",
          "premium": "62.00",
          "delta": "-0.2979",
          "premiumYield": "0.0395"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "3.1296",
          "peRatio": "57.21",
          "strike": "310.0",
          "expiry": "2026-11-06",
          "premium": "11.85",
          "delta": "-0.3165",
          "premiumYield": "0.0382"
        },
        {
          "ticker": "VRT",
          "netAppreciation": "1.3131",
          "peRatio": "55.77",
          "strike": "230.0",
          "expiry": "2026-11-06",
          "premium": "8.75",
          "delta": "-0.3054",
          "premiumYield": "0.0380"
        },
        {
          "ticker": "WDC",
          "netAppreciation": "7.1457",
          "peRatio": "15.06",
          "strike": "375.0",
          "expiry": "2026-11-06",
          "premium": "14.15",
          "delta": "-0.2927",
          "premiumYield": "0.0377"
        },
        {
          "ticker": "ON",
          "netAppreciation": "0.1699",
          "peRatio": "53.23",
          "strike": "77.0",
          "expiry": "2026-11-06",
          "premium": "2.90",
          "delta": "-0.3062",
          "premiumYield": "0.0377"
        },
        {
          "ticker": "HPE",
          "netAppreciation": "2.5950",
          "peRatio": "37.16",
          "strike": "68.0",
          "expiry": "2026-11-06",
          "premium": "2.46",
          "delta": "-0.3290",
          "premiumYield": "0.0362"
        },
        {
          "ticker": "MRVL",
          "netAppreciation": "2.9150",
          "peRatio": "93.64",
          "strike": "265.0",
          "expiry": "2026-11-06",
          "premium": "9.40",
          "delta": "-0.2944",
          "premiumYield": "0.0355"
        },
        {
          "ticker": "DELL",
          "netAppreciation": "3.8962",
          "peRatio": "33.66",
          "strike": "540.0",
          "expiry": "2026-11-06",
          "premium": "18.20",
          "delta": "-0.2948",
          "premiumYield": "0.0337"
        },
        {
          "ticker": "GLW",
          "netAppreciation": "2.7729",
          "peRatio": "74.89",
          "strike": "150.0",
          "expiry": "2026-11-06",
          "premium": "5.00",
          "delta": "-0.2710",
          "premiumYield": "0.0333"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.6333",
          "peRatio": "44.92",
          "strike": "490.0",
          "expiry": "2026-11-06",
          "premium": "15.65",
          "delta": "-0.3060",
          "premiumYield": "0.0319"
        },
        {
          "ticker": "ANET",
          "netAppreciation": "1.1571",
          "peRatio": "68.09",
          "strike": "200.0",
          "expiry": "2026-11-06",
          "premium": "6.30",
          "delta": "-0.2776",
          "premiumYield": "0.0315"
        },
        {
          "ticker": "VLO",
          "netAppreciation": "2.2808",
          "peRatio": "17.68",
          "strike": "400.0",
          "expiry": "2026-11-06",
          "premium": "11.60",
          "delta": "-0.3117",
          "premiumYield": "0.0290"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.6652",
          "peRatio": "14.64",
          "strike": "1025.0",
          "expiry": "2026-11-06",
          "premium": "29.50",
          "delta": "-0.2979",
          "premiumYield": "0.0288"
        },
        {
          "ticker": "GNRC",
          "netAppreciation": "0.2936",
          "peRatio": "50.88",
          "strike": "200.0",
          "expiry": "2026-11-06",
          "premium": "5.60",
          "delta": "-0.2489",
          "premiumYield": "0.0280"
        },
        {
          "ticker": "FTNT",
          "netAppreciation": "1.4335",
          "peRatio": "66.88",
          "strike": "175.0",
          "expiry": "2026-11-06",
          "premium": "4.80",
          "delta": "-0.2845",
          "premiumYield": "0.0274"
        },
        {
          "ticker": "GEV",
          "netAppreciation": "2.7889",
          "peRatio": "28.59",
          "strike": "935.0",
          "expiry": "2026-11-06",
          "premium": "24.30",
          "delta": "-0.2971",
          "premiumYield": "0.0260"
        },
        {
          "ticker": "TXN",
          "netAppreciation": "0.5102",
          "peRatio": "43.98",
          "strike": "270.0",
          "expiry": "2026-11-06",
          "premium": "6.95",
          "delta": "-0.2802",
          "premiumYield": "0.0257"
        }
      ],
      "counts": {
        "candidates": 503,
        "qualifying": 22
      }
    }
  }
};
