// Auto-generated by ui/build_data.py. Do not edit by hand.
window.SCREENER_DATA = {
  "runDate": "2026-10-09",
  "generatedAt": "2026-10-09T02:27:10",
  "tables": {
    "nasdaq100": {
      "available": true,
      "rows": [
        {
          "ticker": "TER",
          "netAppreciation": "2.0764",
          "peRatio": "54.77",
          "strike": "370.0",
          "expiry": "2026-11-06",
          "premium": "16.90",
          "delta": "-0.3176",
          "premiumYield": "0.0457"
        },
        {
          "ticker": "KLAC",
          "netAppreciation": "1.4818",
          "peRatio": "53.75",
          "strike": "185.0",
          "expiry": "2026-11-06",
          "premium": "8.00",
          "delta": "-0.3240",
          "premiumYield": "0.0432"
        },
        {
          "ticker": "SNDK",
          "netAppreciation": "43.7072",
          "peRatio": "21.82",
          "strike": "1490.0",
          "expiry": "2026-11-06",
          "premium": "61.60",
          "delta": "-0.2972",
          "premiumYield": "0.0413"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "2.9281",
          "peRatio": "55.66",
          "strike": "300.0",
          "expiry": "2026-11-06",
          "premium": "11.50",
          "delta": "-0.3100",
          "premiumYield": "0.0383"
        },
        {
          "ticker": "MRVL",
          "netAppreciation": "2.7912",
          "peRatio": "90.35",
          "strike": "255.0",
          "expiry": "2026-11-06",
          "premium": "9.15",
          "delta": "-0.2908",
          "premiumYield": "0.0359"
        },
        {
          "ticker": "FTNT",
          "netAppreciation": "1.3540",
          "peRatio": "66.82",
          "strike": "175.0",
          "expiry": "2026-11-06",
          "premium": "6.00",
          "delta": "-0.2920",
          "premiumYield": "0.0343"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.5247",
          "peRatio": "43.97",
          "strike": "480.0",
          "expiry": "2026-11-06",
          "premium": "16.00",
          "delta": "-0.3097",
          "premiumYield": "0.0333"
        },
        {
          "ticker": "WDC",
          "netAppreciation": "7.1095",
          "peRatio": "14.61",
          "strike": "365.0",
          "expiry": "2026-11-06",
          "premium": "11.45",
          "delta": "-0.2943",
          "premiumYield": "0.0314"
        },
        {
          "ticker": "TXN",
          "netAppreciation": "0.4858",
          "peRatio": "43.87",
          "strike": "270.0",
          "expiry": "2026-11-06",
          "premium": "7.95",
          "delta": "-0.2894",
          "premiumYield": "0.0294"
        },
        {
          "ticker": "CDNS",
          "netAppreciation": "0.2478",
          "peRatio": "69.35",
          "strike": "335.0",
          "expiry": "2026-11-06",
          "premium": "9.80",
          "delta": "-0.3536",
          "premiumYield": "0.0293"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.2378",
          "peRatio": "13.94",
          "strike": "975.0",
          "expiry": "2026-11-06",
          "premium": "26.35",
          "delta": "-0.2952",
          "premiumYield": "0.0270"
        }
      ],
      "counts": {
        "candidates": 100,
        "qualifying": 11
      }
    },
    "sp500": {
      "available": true,
      "rows": [
        {
          "ticker": "TWLO",
          "netAppreciation": "2.9874",
          "peRatio": "38.14",
          "strike": "255.0",
          "expiry": "2026-11-06",
          "premium": "12.50",
          "delta": "-0.3142",
          "premiumYield": "0.0490"
        },
        {
          "ticker": "COHR",
          "netAppreciation": "2.0636",
          "peRatio": "73.39",
          "strike": "280.0",
          "expiry": "2026-11-06",
          "premium": "13.60",
          "delta": "-0.3119",
          "premiumYield": "0.0486"
        },
        {
          "ticker": "TER",
          "netAppreciation": "2.0764",
          "peRatio": "54.77",
          "strike": "370.0",
          "expiry": "2026-11-06",
          "premium": "16.90",
          "delta": "-0.3176",
          "premiumYield": "0.0457"
        },
        {
          "ticker": "RDDT",
          "netAppreciation": "1.2038",
          "peRatio": "36.39",
          "strike": "145.0",
          "expiry": "2026-11-06",
          "premium": "6.50",
          "delta": "-0.3095",
          "premiumYield": "0.0448"
        },
        {
          "ticker": "KLAC",
          "netAppreciation": "1.4818",
          "peRatio": "53.75",
          "strike": "185.0",
          "expiry": "2026-11-06",
          "premium": "8.00",
          "delta": "-0.3240",
          "premiumYield": "0.0432"
        },
        {
          "ticker": "SNDK",
          "netAppreciation": "43.7072",
          "peRatio": "21.82",
          "strike": "1490.0",
          "expiry": "2026-11-06",
          "premium": "61.60",
          "delta": "-0.2972",
          "premiumYield": "0.0413"
        },
        {
          "ticker": "HOOD",
          "netAppreciation": "3.1719",
          "peRatio": "47.14",
          "strike": "99.0",
          "expiry": "2026-11-06",
          "premium": "3.90",
          "delta": "-0.2910",
          "premiumYield": "0.0394"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "2.9281",
          "peRatio": "55.66",
          "strike": "300.0",
          "expiry": "2026-11-06",
          "premium": "11.50",
          "delta": "-0.3100",
          "premiumYield": "0.0383"
        },
        {
          "ticker": "CIEN",
          "netAppreciation": "5.3119",
          "peRatio": "95.29",
          "strike": "395.0",
          "expiry": "2026-11-06",
          "premium": "15.10",
          "delta": "-0.2964",
          "premiumYield": "0.0382"
        },
        {
          "ticker": "VRT",
          "netAppreciation": "1.2597",
          "peRatio": "55.14",
          "strike": "225.0",
          "expiry": "2026-11-06",
          "premium": "8.20",
          "delta": "-0.2914",
          "premiumYield": "0.0364"
        },
        {
          "ticker": "MRVL",
          "netAppreciation": "2.7912",
          "peRatio": "90.35",
          "strike": "255.0",
          "expiry": "2026-11-06",
          "premium": "9.15",
          "delta": "-0.2908",
          "premiumYield": "0.0359"
        },
        {
          "ticker": "HUM",
          "netAppreciation": "0.6168",
          "peRatio": "36.59",
          "strike": "355.0",
          "expiry": "2026-11-06",
          "premium": "12.60",
          "delta": "-0.2902",
          "premiumYield": "0.0355"
        },
        {
          "ticker": "FTNT",
          "netAppreciation": "1.3540",
          "peRatio": "66.82",
          "strike": "175.0",
          "expiry": "2026-11-06",
          "premium": "6.00",
          "delta": "-0.2920",
          "premiumYield": "0.0343"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.5247",
          "peRatio": "43.97",
          "strike": "480.0",
          "expiry": "2026-11-06",
          "premium": "16.00",
          "delta": "-0.3097",
          "premiumYield": "0.0333"
        },
        {
          "ticker": "DELL",
          "netAppreciation": "3.8427",
          "peRatio": "33.40",
          "strike": "535.0",
          "expiry": "2026-11-06",
          "premium": "17.70",
          "delta": "-0.2915",
          "premiumYield": "0.0331"
        },
        {
          "ticker": "HPE",
          "netAppreciation": "2.5610",
          "peRatio": "36.60",
          "strike": "66.0",
          "expiry": "2026-11-06",
          "premium": "2.09",
          "delta": "-0.2937",
          "premiumYield": "0.0317"
        },
        {
          "ticker": "WDC",
          "netAppreciation": "7.1095",
          "peRatio": "14.61",
          "strike": "365.0",
          "expiry": "2026-11-06",
          "premium": "11.45",
          "delta": "-0.2943",
          "premiumYield": "0.0314"
        },
        {
          "ticker": "GLW",
          "netAppreciation": "2.3703",
          "peRatio": "70.11",
          "strike": "140.0",
          "expiry": "2026-11-06",
          "premium": "4.35",
          "delta": "-0.2677",
          "premiumYield": "0.0311"
        },
        {
          "ticker": "GEV",
          "netAppreciation": "2.7643",
          "peRatio": "28.65",
          "strike": "940.0",
          "expiry": "2026-11-06",
          "premium": "28.60",
          "delta": "-0.3035",
          "premiumYield": "0.0304"
        },
        {
          "ticker": "ANET",
          "netAppreciation": "1.0738",
          "peRatio": "66.55",
          "strike": "195.0",
          "expiry": "2026-11-06",
          "premium": "5.80",
          "delta": "-0.2728",
          "premiumYield": "0.0297"
        },
        {
          "ticker": "TXN",
          "netAppreciation": "0.4858",
          "peRatio": "43.87",
          "strike": "270.0",
          "expiry": "2026-11-06",
          "premium": "7.95",
          "delta": "-0.2894",
          "premiumYield": "0.0294"
        },
        {
          "ticker": "CDNS",
          "netAppreciation": "0.2478",
          "peRatio": "69.35",
          "strike": "335.0",
          "expiry": "2026-11-06",
          "premium": "9.80",
          "delta": "-0.3536",
          "premiumYield": "0.0293"
        },
        {
          "ticker": "GNRC",
          "netAppreciation": "0.3025",
          "peRatio": "51.59",
          "strike": "200.0",
          "expiry": "2026-11-06",
          "premium": "5.70",
          "delta": "-0.2349",
          "premiumYield": "0.0285"
        },
        {
          "ticker": "APA",
          "netAppreciation": "0.8795",
          "peRatio": "9.61",
          "strike": "43.0",
          "expiry": "2026-11-06",
          "premium": "1.21",
          "delta": "-0.3150",
          "premiumYield": "0.0281"
        },
        {
          "ticker": "PSX",
          "netAppreciation": "1.2337",
          "peRatio": "16.09",
          "strike": "270.0",
          "expiry": "2026-11-06",
          "premium": "7.50",
          "delta": "-0.3356",
          "premiumYield": "0.0278"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.2378",
          "peRatio": "13.94",
          "strike": "975.0",
          "expiry": "2026-11-06",
          "premium": "26.35",
          "delta": "-0.2952",
          "premiumYield": "0.0270"
        },
        {
          "ticker": "TPR",
          "netAppreciation": "1.6657",
          "peRatio": "15.93",
          "strike": "110.0",
          "expiry": "2026-11-06",
          "premium": "2.80",
          "delta": "-0.3261",
          "premiumYield": "0.0255"
        },
        {
          "ticker": "FCX",
          "netAppreciation": "0.4930",
          "peRatio": "35.04",
          "strike": "67.0",
          "expiry": "2026-11-06",
          "premium": "1.69",
          "delta": "-0.2987",
          "premiumYield": "0.0252"
        }
      ],
      "counts": {
        "candidates": 503,
        "qualifying": 28
      }
    }
  }
};
