// Auto-generated by ui/build_data.py. Do not edit by hand.
window.SCREENER_DATA = {
  "runDate": "2026-10-08",
  "generatedAt": "2026-10-08T04:47:29",
  "tables": {
    "nasdaq100": {
      "available": true,
      "rows": [
        {
          "ticker": "TER",
          "netAppreciation": "2.2034",
          "peRatio": "56.56",
          "strike": "400.0",
          "expiry": "2026-11-06",
          "premium": "29.74",
          "delta": "-0.0001",
          "premiumYield": "0.0743"
        },
        {
          "ticker": "WDC",
          "netAppreciation": "7.1457",
          "peRatio": "15.27",
          "strike": "400.0",
          "expiry": "2026-11-06",
          "premium": "27.82",
          "delta": "-0.0001",
          "premiumYield": "0.0696"
        },
        {
          "ticker": "SNDK",
          "netAppreciation": "46.0117",
          "peRatio": "22.51",
          "strike": "1640.0",
          "expiry": "2026-11-06",
          "premium": "102.32",
          "delta": "-0.0000",
          "premiumYield": "0.0624"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "3.1296",
          "peRatio": "57.21",
          "strike": "310.0",
          "expiry": "2026-11-06",
          "premium": "13.49",
          "delta": "-0.0001",
          "premiumYield": "0.0435"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.6333",
          "peRatio": "45.75",
          "strike": "490.0",
          "expiry": "2026-11-06",
          "premium": "16.93",
          "delta": "-0.0001",
          "premiumYield": "0.0346"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.6652",
          "peRatio": "14.07",
          "strike": "1020.0",
          "expiry": "2026-11-06",
          "premium": "28.87",
          "delta": "-0.0001",
          "premiumYield": "0.0283"
        },
        {
          "ticker": "KLAC",
          "netAppreciation": "1.5488",
          "peRatio": "53.93",
          "strike": "175.0",
          "expiry": "2026-11-06",
          "premium": "4.89",
          "delta": "-0.0003",
          "premiumYield": "0.0279"
        }
      ],
      "counts": {
        "candidates": 100,
        "qualifying": 7
      }
    },
    "sp500": {
      "available": true,
      "rows": [
        {
          "ticker": "GNRC",
          "netAppreciation": "0.2936",
          "peRatio": "50.88",
          "strike": "215.0",
          "expiry": "2026-11-06",
          "premium": "19.23",
          "delta": "-0.0001",
          "premiumYield": "0.0894"
        },
        {
          "ticker": "TER",
          "netAppreciation": "2.2034",
          "peRatio": "56.56",
          "strike": "400.0",
          "expiry": "2026-11-06",
          "premium": "29.74",
          "delta": "-0.0001",
          "premiumYield": "0.0743"
        },
        {
          "ticker": "TWLO",
          "netAppreciation": "3.0301",
          "peRatio": "37.76",
          "strike": "265.0",
          "expiry": "2026-11-06",
          "premium": "19.45",
          "delta": "-0.0001",
          "premiumYield": "0.0734"
        },
        {
          "ticker": "WDC",
          "netAppreciation": "7.1457",
          "peRatio": "15.27",
          "strike": "400.0",
          "expiry": "2026-11-06",
          "premium": "27.82",
          "delta": "-0.0001",
          "premiumYield": "0.0696"
        },
        {
          "ticker": "SNDK",
          "netAppreciation": "46.0117",
          "peRatio": "22.51",
          "strike": "1640.0",
          "expiry": "2026-11-06",
          "premium": "102.32",
          "delta": "-0.0000",
          "premiumYield": "0.0624"
        },
        {
          "ticker": "VRT",
          "netAppreciation": "1.3131",
          "peRatio": "55.77",
          "strike": "240.0",
          "expiry": "2026-11-06",
          "premium": "14.83",
          "delta": "-0.0003",
          "premiumYield": "0.0618"
        },
        {
          "ticker": "COHR",
          "netAppreciation": "2.4184",
          "peRatio": "82.20",
          "strike": "315.0",
          "expiry": "2026-11-06",
          "premium": "19.21",
          "delta": "-0.0002",
          "premiumYield": "0.0610"
        },
        {
          "ticker": "CBOE",
          "netAppreciation": "0.3788",
          "peRatio": "21.95",
          "strike": "265.0",
          "expiry": "2026-11-06",
          "premium": "16.16",
          "delta": "-0.0001",
          "premiumYield": "0.0610"
        },
        {
          "ticker": "ANET",
          "netAppreciation": "1.1571",
          "peRatio": "68.09",
          "strike": "210.0",
          "expiry": "2026-11-06",
          "premium": "10.13",
          "delta": "-0.0003",
          "premiumYield": "0.0482"
        },
        {
          "ticker": "LRCX",
          "netAppreciation": "3.1296",
          "peRatio": "57.21",
          "strike": "310.0",
          "expiry": "2026-11-06",
          "premium": "13.49",
          "delta": "-0.0001",
          "premiumYield": "0.0435"
        },
        {
          "ticker": "CVS",
          "netAppreciation": "0.4401",
          "peRatio": "22.73",
          "strike": "87.0",
          "expiry": "2026-11-06",
          "premium": "3.75",
          "delta": "-0.0007",
          "premiumYield": "0.0431"
        },
        {
          "ticker": "HOOD",
          "netAppreciation": "3.2761",
          "peRatio": "48.24",
          "strike": "103.0",
          "expiry": "2026-11-06",
          "premium": "4.40",
          "delta": "-0.0001",
          "premiumYield": "0.0427"
        },
        {
          "ticker": "DELL",
          "netAppreciation": "3.8962",
          "peRatio": "33.66",
          "strike": "545.0",
          "expiry": "2026-11-06",
          "premium": "22.52",
          "delta": "-0.0001",
          "premiumYield": "0.0413"
        },
        {
          "ticker": "EBAY",
          "netAppreciation": "0.6482",
          "peRatio": "22.56",
          "strike": "105.0",
          "expiry": "2026-11-06",
          "premium": "4.33",
          "delta": "-0.0008",
          "premiumYield": "0.0412"
        },
        {
          "ticker": "BMY",
          "netAppreciation": "0.2473",
          "peRatio": "13.15",
          "strike": "59.0",
          "expiry": "2026-11-06",
          "premium": "2.16",
          "delta": "-0.0003",
          "premiumYield": "0.0366"
        },
        {
          "ticker": "AMAT",
          "netAppreciation": "1.6333",
          "peRatio": "45.75",
          "strike": "490.0",
          "expiry": "2026-11-06",
          "premium": "16.93",
          "delta": "-0.0001",
          "premiumYield": "0.0346"
        },
        {
          "ticker": "HUM",
          "netAppreciation": "0.6713",
          "peRatio": "37.48",
          "strike": "350.0",
          "expiry": "2026-11-06",
          "premium": "12.00",
          "delta": "-0.0001",
          "premiumYield": "0.0343"
        },
        {
          "ticker": "DLTR",
          "netAppreciation": "0.6739",
          "peRatio": "14.15",
          "strike": "110.0",
          "expiry": "2026-11-06",
          "premium": "3.72",
          "delta": "-0.0004",
          "premiumYield": "0.0338"
        },
        {
          "ticker": "GEV",
          "netAppreciation": "2.7889",
          "peRatio": "28.59",
          "strike": "935.0",
          "expiry": "2026-11-06",
          "premium": "29.25",
          "delta": "-0.0001",
          "premiumYield": "0.0313"
        },
        {
          "ticker": "GM",
          "netAppreciation": "0.7943",
          "peRatio": "36.81",
          "strike": "79.0",
          "expiry": "2026-11-06",
          "premium": "2.46",
          "delta": "-0.0007",
          "premiumYield": "0.0311"
        },
        {
          "ticker": "FCX",
          "netAppreciation": "0.5168",
          "peRatio": "35.75",
          "strike": "68.0",
          "expiry": "2026-11-06",
          "premium": "2.10",
          "delta": "-0.0004",
          "premiumYield": "0.0309"
        },
        {
          "ticker": "ULTA",
          "netAppreciation": "0.4964",
          "peRatio": "19.88",
          "strike": "530.0",
          "expiry": "2026-11-06",
          "premium": "16.15",
          "delta": "-0.0001",
          "premiumYield": "0.0305"
        },
        {
          "ticker": "C",
          "netAppreciation": "1.1190",
          "peRatio": "13.88",
          "strike": "124.0",
          "expiry": "2026-11-06",
          "premium": "3.73",
          "delta": "-0.0004",
          "premiumYield": "0.0301"
        },
        {
          "ticker": "IBKR",
          "netAppreciation": "1.4008",
          "peRatio": "34.82",
          "strike": "83.0",
          "expiry": "2026-11-06",
          "premium": "2.45",
          "delta": "-0.0004",
          "premiumYield": "0.0295"
        },
        {
          "ticker": "MU",
          "netAppreciation": "9.6652",
          "peRatio": "14.07",
          "strike": "1020.0",
          "expiry": "2026-11-06",
          "premium": "28.87",
          "delta": "-0.0001",
          "premiumYield": "0.0283"
        },
        {
          "ticker": "KLAC",
          "netAppreciation": "1.5488",
          "peRatio": "53.93",
          "strike": "175.0",
          "expiry": "2026-11-06",
          "premium": "4.89",
          "delta": "-0.0003",
          "premiumYield": "0.0279"
        },
        {
          "ticker": "CAT",
          "netAppreciation": "1.1501",
          "peRatio": "37.16",
          "strike": "765.0",
          "expiry": "2026-11-06",
          "premium": "21.25",
          "delta": "-0.0001",
          "premiumYield": "0.0278"
        },
        {
          "ticker": "ON",
          "netAppreciation": "0.1699",
          "peRatio": "53.23",
          "strike": "74.0",
          "expiry": "2026-11-06",
          "premium": "2.05",
          "delta": "-0.0007",
          "premiumYield": "0.0277"
        },
        {
          "ticker": "GE",
          "netAppreciation": "0.6383",
          "peRatio": "36.49",
          "strike": "295.0",
          "expiry": "2026-11-06",
          "premium": "8.10",
          "delta": "-0.0001",
          "premiumYield": "0.0275"
        },
        {
          "ticker": "CIEN",
          "netAppreciation": "5.8421",
          "peRatio": "99.88",
          "strike": "390.0",
          "expiry": "2026-11-06",
          "premium": "10.60",
          "delta": "-0.0000",
          "premiumYield": "0.0272"
        },
        {
          "ticker": "GLW",
          "netAppreciation": "2.7729",
          "peRatio": "74.89",
          "strike": "145.0",
          "expiry": "2026-11-06",
          "premium": "3.70",
          "delta": "-0.0003",
          "premiumYield": "0.0255"
        },
        {
          "ticker": "GS",
          "netAppreciation": "0.8590",
          "peRatio": "13.70",
          "strike": "860.0",
          "expiry": "2026-11-06",
          "premium": "21.59",
          "delta": "-0.0000",
          "premiumYield": "0.0251"
        }
      ],
      "counts": {
        "candidates": 503,
        "qualifying": 32
      }
    }
  }
};
